### ISSUE TITLE
Handle duplicate message id better

### ISSUE THREAD

**Issue by chrlns** [chrlns/sonews#67]
SEVERE: VirtualThread[#6835]/runnable@ForkJoinPool-1-worker-3521: Database connection was closed (restart 0).
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "article_ids_message_id_key"
  Detail: Key (message_id)=(<67a02422761e3fc4da3fb4561889a2f9@localhost>) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:322)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:256)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:276)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:276)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:276)
	at org.sonews.storage.impl.jdbc.JDBCDatabase.addArticle(JDBCDatabase.java:276)

**Comment by chrlns** [comment]
The commit solves another synchronization problem, I'm not sure if this is also fixed but closed for now.
